general:
  statisticsAllowed: true

database:
  useMySQL: false
  host:
  port: 3306
  user:
  password:

chat:
  enabled: true

  format:
    format: "{prefix }&7{username}{ suffix}&8 > &f{message}"
    translateChatColors: true

  joinMessage:
    show: true
    message: "&7[&a+&7] &7{username}"

  quitMessage:
    show: true
    message: "&7[&a+&7] &7{username}"

  # may break some plugins
  worldChat:
    enabled: false
    considerRange: false
    range: 50

filter:
  enabled: true
  filterMode: BLOCK
  # TODO implement
  whitelist:
    - rex2go.eu

antiSpam:
  enabled: true
  capsThreshold: 0.5
  spaceThreshold: 0.3

format:
  privateMessage: "&8MSG &7[{sender} -> {receiver}]&8: &f{message}"
  broadcast: "&f[&cBroadcast&f] {message}"

notification:
  filter:
    enabled: true

version: 6